# Generated by Django 4.2.23 on 2026-08-03 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number starting with 6, 7, 8 or 9.', regex='^[6-9][0-9]{9}$')]),
        ),
    ]
