# Generated by Django 4.2.23 on 2026-07-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_seller_alter_productrequest_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Beauty', 'Beauty'), ('Home', 'Home'), ('Sports', 'Sports')], default='Electronics', max_length=30),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Beauty', 'Beauty'), ('Home', 'Home'), ('Sports', 'Sports')], default='Electronics', max_length=30),
        ),
    ]
